import { type Metadata } from 'next'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'
import '@/app/styles/globals.css'
import Image from 'next/image'
import logo from '@/app/Images/logo.jpg'
import Link from 'next/link'
export const metadata: Metadata = {
    title: 'SPARK: Reigniting learning and innovation',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
                <ul className="navbar">
                    <li className="no-hover"><Image src={logo} alt="SPARK Logo" width={50} height={60} style={{ transform: 'translate(0px, 0px)' }} /></li>
                    <li className="no-hover" style={{ transform: 'translate(-5px, -18px)' }}><Link href="/app"><h1 className='h1'>SPARK</h1></Link></li>
                    <li><a href="https://www.rva.gov/parks-recreation/powhatan-community-center">Contact Us</a></li>
                    <li><a href="/sessions">Sessions & Coming Events</a></li>
                    <li style={{ float: 'right' }}>
                        <a style={{ gap: '16px' }}>
                            <SignedOut>
                                <SignInButton />
                                <SignUpButton />
                            </SignedOut></a></li>
                    <li style={{ float: 'right' }}>
                        <SignedIn>
                            <UserButton />
                        </SignedIn> </li>
                </ul>
                <html lang="en">
                    <body>
                        {children}
                    </body>

                </html>
            </ClerkProvider >

        </>
    )
} 
