import { type Metadata } from 'next'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'
import Link from 'next/link'
import Image from 'next/image'
import logo from '@/app/Images/logo.png'
import '@/app/styles/globals.css'

export const metadata: Metadata = {
    title: 'SPARK: Reigniting learning and innovation',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>

                <ul className="navbar">
                    <Link href="/"><Image src={logo} alt="logo" width={250} height={140} /></Link>
                    <li><a href="https://www.rva.gov/parks-recreation/powhatan-community-center">Contact Us</a></li>
                    <li><a href="/sessions">Sessions & Coming Events</a></li>


                    <li>
                        <a style={{ gap: '16px' }}>
                            <SignedOut>
                                <SignInButton />
                                <SignUpButton />
                            </SignedOut></a></li>

                    <li><SignedIn>
                        <UserButton />
                    </SignedIn> </li>
                </ul>
                <html lang="en">
                    <meta charSet="UTF-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                    <body>
                        {children}
                    </body>
                </html>
            </ClerkProvider >

        </>
    )
} 
